photomosaic:photomosaic.o
	gcc -o photomosaic photomosaic.o

cria_arquivo:cria_arquivo.o
	gcc -o cria_arquivo cria_arquivo.o

photomosaic.o:photomosaic.c
	gcc -c photomosaic.c

cria_arquivo.o:cria_arquivo.c
	gcc -c cria_arquivo.c
